Medium/Medium/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),

    path('', include('blog.urls')),
    path('account/', include('user_info.urls'))
]

Medium/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.Home.as_view(), name='Home'),
    path('<str:author>/<int:pk>/<slug:slug>', views.PostDetail.as_view(), name='post_detail'),
    path('tags/<str:tag>',views.TagRelatedPost.as_view(), name='TagRelatedPost'),
    path('pdf/<str:post>', views.PrintToPDF.as_view(), name='pdf'),
    path('t', views.test, name='test')
]

Medium/user_info/urls.py
from django.urls import path, include
from . import views

app_name = 'user_info'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('newUser', views.CreateUser.as_view(), name='createuser'),
    path('users/<str:username>', views.AuthorBio.as_view(), name='authorbio'), 
    path('notifications', views.Notifications.as_view(), name='notifications'), 
    path('<str:username>/membership', views.MembershipView.as_view(), name='membership')
]

Medium/templates/base.html
{# This is base page for homepage when user is not logged in #}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    {% block head %}{% endblock head %}
    <title>Document</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}{% endblock content %}    
    </div>
</body>
</html>

<style>{% block style %}{% endblock style %}</style>

{% block script %}{% endblock script %}

Medium/templates/base_nologin.html
{# This is base page for homepage when user is not logged in #}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container">
        <h3>Quote banner</h3>
    {% block content %}{% endblock content %}
    </div>
</body>
</html>

Medium/templates/loginnavbar.html
<!DOCTYPE html>
<div class='container-fluid'>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'blog:Home' %}">Home</a>
            <a class="nav-link active" href="{% url 'user_info:login' %}">login</a>
            <a class="nav-link active" href="{% url 'user_info:logout' %}">logout</a>
            {% comment %} <a class="nav-link active" href="{% url 'user_info:password_change' %}">password_change</a>
            <a class="nav-link active" href="{% url 'user_info:password_change_done' %}">password_change_done</a>
            <a class="nav-link active" href="{% url 'user_info:password_reset' %}">password_reset</a>
            <a class="nav-link active" href="{% url 'user_info:password_reset_done' %}">password_reset_done</a>
            <a class="nav-link active" href="{% url 'user_info:password_reset_complete' %}">password_reset_complete</a> {% endcomment %}
            
        </div>
    </nav>
    Current User = {{request.user}}
    <br>
</div>

Medium/templates/navbar.html
<!DOCTYPE html>
<div class='container-fluid'>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'blog:Home' %}">Home</a>
            <a class="nav-link active" href="{% url 'user_info:login' %}">login</a>
            <a class="nav-link active" href="{% url 'user_info:logout' %}">logout</a>
            <a href="{% url 'user_info:notifications' %}" class="nav-link active">Notifications</a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'user_info:membership' request.user.username%}" class='nav-link active'>Membership</a>
            {% endif %}
            {% comment %} <a class="nav-link active" href="{% url 'user_info:password_change' %}">password_change</a>
            <a class="nav-link active" href="{% url 'user_info:password_change_done' %}">password_change_done</a>
            <a class="nav-link active" href="{% url 'user_info:password_reset' %}">password_reset</a>
            <a class="nav-link active" href="{% url 'user_info:password_reset_done' %}">password_reset_done</a>
            <a class="nav-link active" href="{% url 'user_info:password_reset_complete' %}">password_reset_complete</a> {% endcomment %}
            
        </div>
    </nav>
    User = {{request.user}}
    <br>
    Profile = {{request.user.profile}}
    <br>
</div>